### ISSUE TITLE
change from %s to {}

### ISSUE THREAD

**Issue by yassu** [visio2img/visio2img#4]
`%s` may be going to deplicate for python.

I think that it is better that it is used `{}` syntax.

**Comment by tk0miya** [comment]
As far as I know, `%s` notation will not be deprecated.
If your request comes from the deprecation, please investigate is it really or not.
If not, either way is fine for me. I don't have strong opinion between two notations.

**Comment by yassu** [comment]
This is a my misunderstand.

I will delete this issue.
